on:
  #Set to trigger on every merge to main, not just a closed PR.
  pull_request_target:
    branches:
      - main
    types: ["closed"]

jobs:
<<<<<<< HEAD
  cherry_pick:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    if: github.event.pull_request.merged == 'true'
=======
  cherry_pick_patch:
    runs-on: ubuntu-latest
    name: Cherry pick into main
    # if: contains(github.event.pull_request.labels.*.name, 'main')
>>>>>>> e83a052180a0c29096a16dd8aa038b1cd4f9f4cd
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
<<<<<<< HEAD
          ref: ${{github.event.pull_request.head.ref}}
          repository: ${{github.event.pull_request.head.repo.full_name}}
      - name: Cherry pick
        run: |
          git remote add <fork> <${{github.event.pull_request.head.repo.full_name}}>
          git fetch fork
          git cherry-pick ${{github.event.pull_request.head.number}}
          git push origin main
=======
          fetch-depth: 0
      - name: Cherry pick into main
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.2
        with:
          branch: main
          labels: |
            cherry-pick

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>>>>>>> e83a052180a0c29096a16dd8aa038b1cd4f9f4cd
